import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router"
import { useEffect, type ReactNode } from "react"
import { Button } from "@/components/ui/button"
import appCss from "../styles.css?url"
import { reportLovableError } from "../lib/lovable-error-reporting"
function NotFoundComponent(){return <div className="grid min-h-screen place-items-center bg-background px-4 text-center"><div><p className="font-display text-8xl font-bold text-primary">404</p><h1 className="mt-2 text-2xl font-semibold">Page not found</h1><p className="mt-2 text-sm text-muted-foreground">This FITCORE screen does not exist.</p><Button asChild className="mt-6"><Link to="/">Return to dashboard</Link></Button></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="grid min-h-screen place-items-center bg-background px-4 text-center"><div><h1 className="text-2xl font-semibold">This screen did not load</h1><p className="mt-2 text-sm text-muted-foreground">Please try again.</p><Button className="mt-6" onClick={()=>{router.invalidate();reset()}}>Try again</Button></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Space+Grotesk:wght@500;600;700&display=swap"},{rel:"icon",href:"/favicon.ico",type:"image/x-icon"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent})
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const{queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><Outlet/></QueryClientProvider>}
