import { Link, useRouterState } from "@tanstack/react-router"
import { Activity, CalendarCheck, CreditCard, Dumbbell, History, LayoutDashboard, LogOut, Menu, Search, ShieldCheck, UserRoundSearch, Users, WalletCards, Bell } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Sheet, SheetContent, SheetTitle, SheetTrigger, SheetClose } from "@/components/ui/sheet"
import { cn } from "@/lib/utils"
import type { ReactNode } from "react"
const links=[
 {to:"/",label:"Dashboard",icon:LayoutDashboard,group:"Overview"},{to:"/members",label:"Members",icon:Users,group:"Manage"},{to:"/member-search",label:"Member Search",icon:UserRoundSearch,group:"Manage"},{to:"/attendance",label:"Attendance",icon:CalendarCheck,group:"Manage"},{to:"/trainers",label:"Trainers",icon:Dumbbell,group:"Manage"},{to:"/plans",label:"Membership Plans",icon:ShieldCheck,group:"Manage"},{to:"/payments",label:"Payments",icon:CreditCard,group:"Finance"},{to:"/payment-history",label:"Payment History",icon:History,group:"Finance"},{to:"/pending-fees",label:"Pending Fees",icon:WalletCards,group:"Finance"},
] as const
function Brand(){return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary shadow-brand"><Dumbbell className="size-5 text-primary-foreground"/></div><div><p className="font-display text-lg font-bold leading-none text-foreground">FITCORE</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-[0.22em] text-muted-foreground">Gym Manager</p></div></div>}
function Nav(){const path=useRouterState({select:s=>s.location.pathname});return <nav className="mt-7 flex-1 overflow-y-auto pr-1">{["Overview","Manage","Finance"].map(group=><div key={group} className="mb-5"><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground/70">{group}</p><div className="space-y-1">{links.filter(x=>x.group===group).map(item=>{const Icon=item.icon;const active=path===item.to;return <SheetClose key={item.to} asChild><Link to={item.to} className={cn("flex items-center gap-3 rounded-xl border border-transparent px-3 py-2.5 text-sm font-medium text-muted-foreground transition-all hover:bg-secondary hover:text-foreground",active&&"border-primary/25 bg-primary/12 text-foreground shadow-inner-soft")}><Icon className={cn("size-4",active&&"text-primary")}/><span>{item.label}</span>{item.label==="Pending Fees"&&<span className="ml-auto rounded-full bg-primary/15 px-2 py-0.5 text-[10px] text-primary">27</span>}</Link></SheetClose>})}</div></div>)}</nav>}
function Sidebar(){return <div className="flex h-full flex-col"><Brand/><Nav/><div className="glass-panel mt-3 flex items-center gap-3 rounded-xl p-3"><div className="grid size-9 shrink-0 place-items-center rounded-full bg-primary/15 text-xs font-bold text-primary">AR</div><div className="min-w-0"><p className="truncate text-sm font-semibold">Aarav Rao</p><p className="text-xs text-muted-foreground">Administrator</p></div><Link to="/login" aria-label="Sign out" className="ml-auto text-muted-foreground hover:text-primary"><LogOut className="size-4"/></Link></div></div>}
export function AppShell({children}:{children:ReactNode}){return <div className="min-h-screen bg-background text-foreground"><div className="app-glow"/><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-border bg-sidebar/90 p-5 backdrop-blur-xl md:block"><Sidebar/></aside><div className="relative md:pl-64"><header className="sticky top-0 z-20 grid h-16 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-border bg-background/80 px-4 backdrop-blur-xl md:px-8"><Sheet><SheetTrigger asChild><Button variant="outline" size="icon" className="md:hidden" aria-label="Open menu"><Menu/></Button></SheetTrigger><SheetContent side="left" className="w-[286px] border-border bg-sidebar p-5"><SheetTitle className="sr-only">FITCORE navigation</SheetTitle><Sidebar/></SheetContent></Sheet><div className="min-w-0"><p className="text-xs text-muted-foreground">Sunday, 20 September 2026</p><p className="truncate text-sm font-semibold">Good evening, Aarav</p></div><div className="flex items-center gap-2"><Button asChild variant="outline" size="icon" className="hidden sm:inline-flex" aria-label="Search members"><Link to="/member-search"><Search/></Link></Button><Button variant="outline" size="icon" aria-label="Notifications" className="relative"><Bell/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-primary"/></Button></div></header><main className="mx-auto max-w-[1600px] space-y-6 p-4 sm:p-6 md:p-8">{children}</main></div></div>}
