import { useMemo, useState } from "react"
import { CheckCircle2, Clock3, Download, Eye, Filter, SearchCheck, Send, UserCheck } from "lucide-react"
import { AppShell } from "./app-shell"
import { ActionDialog, Notice } from "./forms"
import { GlassCard, PageTitle, SearchBox, StatusBadge, initials } from "./ui"
import { attendance, formatMoney, members, payments, plans, trainers } from "@/lib/fitcore-data"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

type PageKind="members"|"search"|"payments"|"history"|"trainers"|"attendance"|"plans"|"fees"
const titles:Record<PageKind,{eyebrow:string;title:string;desc:string}>={
 members:{eyebrow:"Member management",title:"Members",desc:"Manage member profiles, plans, trainers, and membership status."},
 search:{eyebrow:"Member directory",title:"Member search",desc:"Find any member using their name, phone number, or membership ID."},
 payments:{eyebrow:"Payment management",title:"Payments",desc:"Record membership fees and monitor this month's collections."},
 history:{eyebrow:"Finance",title:"Payment history",desc:"Review every receipt, payment method, and transaction status."},
 trainers:{eyebrow:"Team management",title:"Trainers",desc:"Manage specialties, client load, and daily shifts."},
 attendance:{eyebrow:"Front desk",title:"Attendance",desc:"Track today's check-ins and current gym occupancy."},
 plans:{eyebrow:"Memberships",title:"Membership plans",desc:"Present flexible plans for every training commitment."},
 fees:{eyebrow:"Collections",title:"Pending fees",desc:"Follow up overdue payments and protect membership continuity."},
}
function Shell({kind,action,children}:{kind:PageKind;action?:React.ReactNode;children:React.ReactNode}){const t=titles[kind];return <AppShell><PageTitle eyebrow={t.eyebrow} title={t.title} description={t.desc} action={action}/>{children}</AppShell>}
function Toolbar({query,setQuery,placeholder="Search records..."}:{query:string;setQuery:(v:string)=>void;placeholder?:string}){return <div className="flex flex-col gap-3 sm:flex-row"><SearchBox value={query} onChange={setQuery} placeholder={placeholder}/><Select defaultValue="all"><SelectTrigger className="h-10 w-full rounded-xl bg-secondary/60 sm:w-40"><Filter className="size-4"/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All status</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="overdue">Overdue</SelectItem></SelectContent></Select></div>}
function MemberTable({rows=members}:{rows?:typeof members}){return <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead><tr className="border-b border-border text-left text-[11px] uppercase tracking-wider text-muted-foreground"><th className="px-5 py-3 font-medium">Member</th><th className="px-3 py-3 font-medium">Contact</th><th className="px-3 py-3 font-medium">Plan</th><th className="px-3 py-3 font-medium">Trainer</th><th className="px-3 py-3 font-medium">Status</th><th className="px-5 py-3 text-right font-medium">Expires</th></tr></thead><tbody>{rows.map(m=><tr key={m.id} className="border-b border-border/70 hover:bg-secondary/35"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-primary/15 text-xs font-bold text-primary">{initials(m.name)}</span><div><p className="font-semibold">{m.name}</p><p className="text-xs text-muted-foreground">{m.id}</p></div></div></td><td className="px-3 text-muted-foreground">{m.phone}</td><td className="px-3">{m.plan}</td><td className="px-3 text-muted-foreground">{m.trainer}</td><td className="px-3"><StatusBadge status={m.status}/></td><td className="px-5 text-right text-muted-foreground">{m.expires}</td></tr>)}</tbody></table></div>}
export function MembersPage(){const[q,setQ]=useState("");const[note,setNote]=useState("");const rows=members.filter(m=>`${m.name} ${m.id} ${m.phone}`.toLowerCase().includes(q.toLowerCase()));return <Shell kind="members" action={<ActionDialog onSaved={setNote}/>}>{note&&<Notice>{note}</Notice>}<GlassCard className="overflow-hidden"><div className="border-b border-border p-4 sm:p-5"><Toolbar query={q} setQuery={setQ} placeholder="Search members..."/></div><MemberTable rows={rows}/><div className="flex items-center justify-between p-4 text-xs text-muted-foreground"><span>Showing {rows.length} of 1,284 members</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled>Previous</Button><Button size="sm" variant="outline">Next</Button></div></div></GlassCard></Shell>}
export function MemberSearchPage(){const[q,setQ]=useState("");const rows=useMemo(()=>q.trim()?members.filter(m=>`${m.name} ${m.id} ${m.phone}`.toLowerCase().includes(q.toLowerCase())):[],[q]);return <Shell kind="search"><GlassCard className="p-5 sm:p-8"><div className="mx-auto max-w-2xl text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/15 text-primary"><SearchCheck/></div><h2 className="mt-4 font-display text-xl font-semibold">Search the member directory</h2><p className="mt-1 text-sm text-muted-foreground">Enter a name, phone number, or FITCORE ID.</p><div className="mx-auto mt-5 max-w-xl"><SearchBox value={q} onChange={setQ} placeholder="Try Priya or FC-1042"/></div></div></GlassCard>{q&&<GlassCard className="overflow-hidden"><div className="border-b border-border px-5 py-4 text-sm text-muted-foreground">{rows.length} result{rows.length===1?"":"s"} for “{q}”</div>{rows.length?<MemberTable rows={rows}/>:<div className="p-10 text-center text-sm text-muted-foreground">No matching member found.</div>}</GlassCard>}</Shell>}
export function TrainersPage(){const[note,setNote]=useState("");return <Shell kind="trainers" action={<ActionDialog type="trainer" onSaved={setNote}/>}>{note&&<Notice>{note}</Notice>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{trainers.map((t,i)=><GlassCard key={t.name} className="metric-card p-5"><div className="flex items-start justify-between"><div className="grid size-11 place-items-center rounded-xl bg-primary/15 font-display font-bold text-primary">{initials(t.name)}</div><StatusBadge status={t.status}/></div><h2 className="mt-5 font-display text-lg font-semibold">{t.name}</h2><p className="mt-1 text-sm text-primary">{t.specialty}</p><div className="mt-5 space-y-2 border-t border-border pt-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Active clients</span><span>{t.clients}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Shift</span><span>{t.shift}</span></div></div><Button variant="outline" className="mt-4 w-full rounded-xl"><Eye/>View schedule</Button></GlassCard>)}</section></Shell>}
export function AttendancePage(){const[note,setNote]=useState("");return <Shell kind="attendance" action={<Button className="rounded-xl" onClick={()=>setNote("Member FC-1042 checked in at the front desk.")}><UserCheck/>Check in member</Button>}>{note&&<Notice>{note}</Notice>}<section className="grid gap-4 sm:grid-cols-3"><Metric label="Today's check-ins" value="312"/><Metric label="Currently inside" value="47"/><Metric label="Average duration" value="1h 18m"/></section><GlassCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><h2 className="font-display text-lg font-semibold">Today's attendance</h2><span className="text-xs text-muted-foreground">Updated just now</span></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b border-border text-left text-xs text-muted-foreground"><th className="px-5 py-3">Member</th><th className="px-3">Check in</th><th className="px-3">Check out</th><th className="px-3">Duration</th><th className="px-5 text-right">Status</th></tr></thead><tbody>{attendance.map(a=><tr key={a.id} className="border-b border-border/70"><td className="px-5 py-4"><p className="font-semibold">{a.member}</p><p className="text-xs text-muted-foreground">{a.id}</p></td><td className="px-3">{a.checkIn}</td><td className="px-3 text-muted-foreground">{a.checkOut}</td><td className="px-3">{a.duration}</td><td className="px-5 text-right"><StatusBadge status={a.checkOut==="—"?"Present":"Checked out"}/></td></tr>)}</tbody></table></div></GlassCard></Shell>}
function Metric({label,value}:{label:string;value:string}){return <GlassCard className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl font-bold">{value}</p></GlassCard>}
export function PlansPage(){const[note,setNote]=useState("");return <Shell kind="plans" action={<ActionDialog type="plan" onSaved={setNote}/>}>{note&&<Notice>{note}</Notice>}<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{plans.map((p,i)=><GlassCard key={p.name} className={`relative overflow-hidden p-5 ${i===3?"border-primary/40":""}`}>{i===3&&<span className="absolute right-4 top-4 rounded-full bg-primary px-2 py-1 text-[10px] font-bold text-primary-foreground">POPULAR</span>}<p className="text-sm font-semibold text-primary">{p.duration}</p><h2 className="mt-2 font-display text-xl font-bold">{p.name}</h2><p className="mt-4 font-display text-3xl font-bold">{formatMoney(p.price)}<span className="font-sans text-xs font-normal text-muted-foreground"> / plan</span></p><ul className="mt-5 space-y-3">{p.features.map(f=><li key={f} className="flex items-center gap-2 text-sm text-muted-foreground"><CheckCircle2 className="size-4 text-success"/>{f}</li>)}</ul><p className="mt-5 border-t border-border pt-4 text-xs text-muted-foreground">{p.members} active members</p></GlassCard>)}</section></Shell>}
export function PaymentsPage({history=false}:{history?:boolean}){const[q,setQ]=useState("");const[note,setNote]=useState("");const rows=payments.filter(p=>p.member.toLowerCase().includes(q.toLowerCase())||p.receipt.toLowerCase().includes(q.toLowerCase()));return <Shell kind={history?"history":"payments"} action={history?<Button variant="outline" className="rounded-xl" onClick={()=>setNote("Payment report prepared for download.")}><Download/>Export</Button>:<ActionDialog type="payment" onSaved={setNote}/>}>{note&&<Notice>{note}</Notice>} {!history&&<section className="grid gap-4 sm:grid-cols-3"><Metric label="Collected this month" value="₹4.82L"/><Metric label="Transactions" value="186"/><Metric label="Collection rate" value="91.6%"/></section>}<GlassCard className="overflow-hidden"><div className="border-b border-border p-4 sm:p-5"><Toolbar query={q} setQuery={setQ} placeholder="Search receipt or member..."/></div><PaymentTable rows={rows}/></GlassCard></Shell>}
function PaymentTable({rows}:{rows:typeof payments}){return <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b border-border text-left text-xs text-muted-foreground"><th className="px-5 py-3">Receipt</th><th className="px-3">Member</th><th className="px-3">Date</th><th className="px-3">Method</th><th className="px-3">Status</th><th className="px-5 text-right">Amount</th></tr></thead><tbody>{rows.map(p=><tr key={p.receipt} className="border-b border-border/70 hover:bg-secondary/35"><td className="px-5 py-4 font-medium">{p.receipt}</td><td className="px-3">{p.member}</td><td className="px-3 text-muted-foreground">{p.date}</td><td className="px-3">{p.method}</td><td className="px-3"><StatusBadge status={p.status}/></td><td className="px-5 text-right font-semibold">{formatMoney(p.amount)}</td></tr>)}</tbody></table></div>}
export function PendingFeesPage(){const[note,setNote]=useState("");const overdue=members.filter(m=>m.due);return <Shell kind="fees" action={<Button className="rounded-xl" onClick={()=>setNote("Payment reminders queued for all overdue members.")}><Send/>Remind all</Button>}>{note&&<Notice>{note}</Notice>}<section className="grid gap-4 sm:grid-cols-3"><Metric label="Total outstanding" value="₹48,200"/><Metric label="Overdue members" value="27"/><Metric label="Due this week" value="14"/></section><GlassCard className="overflow-hidden"><div className="border-b border-border p-5"><h2 className="font-display text-lg font-semibold">Priority follow-ups</h2></div>{overdue.map((m,i)=><div key={m.id} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b border-border p-5"><div className="flex min-w-0 items-center gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-full bg-primary/15 text-xs font-bold text-primary">{initials(m.name)}</div><div className="min-w-0"><p className="truncate font-semibold">{m.name}</p><p className="text-xs text-muted-foreground">{m.id} · {m.plan} · {i?"5":"12"} days late</p></div></div><div className="text-right"><p className="font-display text-lg font-bold text-primary">{formatMoney(m.due)}</p><Button size="sm" variant="outline" className="mt-2" onClick={()=>setNote(`Reminder sent to ${m.name}.`)}><Send/>Remind</Button></div></div>)}</GlassCard></Shell>}
